[package]
name = "onagre"
version = "0.1.0"
authors = ["Paul Delafosse <paul.delafosse@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["iced/wgpu", "iced/default_system_font", "iced/palette"]
opacity = ["iced/glow", "iced/glow_default_system_font", "iced/palette"]
debug = ["iced/debug"]

[dependencies]
iced = { git = "https://github.com/oknozor/iced", features = ["wgpu", "default_system_font", "palette"] }
iced_native = { git = "https://github.com/oknozor/iced" }
iced_style = { git = "https://github.com/oknozor/iced" }
iced_futures = { git = "https://github.com/oknozor/iced" }
iced_graphics = { git = "https://github.com/oknozor/iced" }
fuzzy-matcher = "0.3.7"
async-std = "1.6.5"
async-process = "1.0.1"
rayon = "1.5.0"
futures = "0.3.7"
dirs = "3.0.1"
anyhow = "1.0.34"
serde_ini = "0.2.0"
serde = "1.0.117"
serde_derive = "1.0.117"
toml = "0.5.7"
shell-words = "^1"
config = "0.10.1"
ignore = "0.4.16"
lazy_static = "1.4.0"
palette = { version = "0.5.0", features = ["serializing"] }

[patch.crates-io]
# patch: transparency (config.composite_alpha_mode = hal::window::CompositeAlphaMode::PREMULTIPLIED)
# https://github.com/hecrj/iced/issues/596
wgpu-core  = { git = "https://github.com/myfreeweb/wgpu", branch = "v0.6-alpha" }
wgpu-types = { git = "https://github.com/myfreeweb/wgpu", branch = "v0.6-alpha" }

