[package]
name = "onagre"
version = "1.0.0-alpha.0"
authors = ["Paul Delafosse <paul.delafosse@protonmail.com>"]
edition = "2018"
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
codegen-units = 1
lto = true

[features]
default = ["iced/wgpu", "iced/default_system_font", "iced/palette", "cli"]
cli = ["structopt"]
debug = ["iced/debug"]

[dependencies]
iced = { version = "0.4.2", features = ["wgpu", "default_system_font", "palette", "svg", "image", "tokio"] }
iced_native = "0.5.0"
iced_style = "0.4.0"
palette = { version = "0.5.0", features = ["serializing"] }
tokio = { version = "1.18.2", features = ["process", "macros", "io-util"] }
sled = "0.34.7"

pop-launcher-toolkit = { git = "https://github.com/pop-os/launcher/" }
structopt = { version = "^0", default-features = false, optional = true }
freedesktop-icons = "0.2.0"

log = { version = "0.4.11" }
env_logger = { version = "0.8.1" }
once_cell = "1.10.0"
anyhow = "1.0.34"
dirs = "4.0"
thiserror = "1.0.31"

serde = { version = "^1", features = ["derive"] }
serde_ini = "0.2.0"
serde_json = "1.0.59"
serde_with = "1.13.0"
ron = "0.6.5"
pest = "2.1.3"
pest_derive = "2.1.0"
font-kit = "0.10.1"
ico = "0.1.0"
regex = "1.5.5"
shell-words = "^1"

[dev-dependencies]
criterion = "0.3"
speculoos = "0.9.0"
pretty_assertions = "1.2.1"

[[bench]]
name = "icon"
harness = false

[[bench]]
name = "database"
harness = false