name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  binary:
    name: Publish binary for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # This should work with only the `include`s but it currently doesn't because of this bug:
        # https://github.community/t5/How-to-use-Git-and-GitHub/GitHub-Actions-Matrix-options-dont-work-as-documented/td-p/29558
        target: [ x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl, armv7-unknown-linux-musleabihf ]
        include:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-musl
          - os: ubuntu-22.04
            target: armv7-unknown-linux-musleabihf

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: Install libssl-dev
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: sudo apt-get update && sudo apt-get install cmake mingw-w64

      - uses: actions/checkout@v1
      - name: Build
        run: ci/action.sh release ${{ matrix.target }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/tar/onagre.tar.gz
          tag: ${{ github.ref }}
          asset_name: onagre-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target }}.tar.gz
